# Generated by Django 4.2.29 on 2026-03-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='campaign_manager.campaign')),
            ],
            options={
                'ordering': ['campaign', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('reward_gold', models.IntegerField(default=0)),
                ('reward_xp', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('epic', 'Epic')], default='medium', max_length=20)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='campaign_manager.campaign')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests_given', to='campaign_manager.npc')),
            ],
            options={
                'ordering': ['campaign', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='campaign_manager.quest')),
            ],
            options={
                'ordering': ['quest', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_notes', models.TextField(blank=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='campaign_manager.quest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_quests', to='campaign_manager.session')),
            ],
            options={
                'unique_together': {('session', 'quest')},
            },
        ),
    ]
